// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"juice/internal/data/ent/predicate"
	"juice/internal/data/ent/userpassword"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPasswordUpdate is the builder for updating UserPassword entities.
type UserPasswordUpdate struct {
	config
	hooks    []Hook
	mutation *UserPasswordMutation
}

// Where appends a list predicates to the UserPasswordUpdate builder.
func (upu *UserPasswordUpdate) Where(ps ...predicate.UserPassword) *UserPasswordUpdate {
	upu.mutation.Where(ps...)
	return upu
}

// SetUserID sets the "user_id" field.
func (upu *UserPasswordUpdate) SetUserID(i int64) *UserPasswordUpdate {
	upu.mutation.ResetUserID()
	upu.mutation.SetUserID(i)
	return upu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (upu *UserPasswordUpdate) SetNillableUserID(i *int64) *UserPasswordUpdate {
	if i != nil {
		upu.SetUserID(*i)
	}
	return upu
}

// AddUserID adds i to the "user_id" field.
func (upu *UserPasswordUpdate) AddUserID(i int64) *UserPasswordUpdate {
	upu.mutation.AddUserID(i)
	return upu
}

// ClearUserID clears the value of the "user_id" field.
func (upu *UserPasswordUpdate) ClearUserID() *UserPasswordUpdate {
	upu.mutation.ClearUserID()
	return upu
}

// SetSalt sets the "salt" field.
func (upu *UserPasswordUpdate) SetSalt(s string) *UserPasswordUpdate {
	upu.mutation.SetSalt(s)
	return upu
}

// SetPwd sets the "pwd" field.
func (upu *UserPasswordUpdate) SetPwd(s string) *UserPasswordUpdate {
	upu.mutation.SetPwd(s)
	return upu
}

// Mutation returns the UserPasswordMutation object of the builder.
func (upu *UserPasswordUpdate) Mutation() *UserPasswordMutation {
	return upu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (upu *UserPasswordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, upu.sqlSave, upu.mutation, upu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upu *UserPasswordUpdate) SaveX(ctx context.Context) int {
	affected, err := upu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (upu *UserPasswordUpdate) Exec(ctx context.Context) error {
	_, err := upu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upu *UserPasswordUpdate) ExecX(ctx context.Context) {
	if err := upu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upu *UserPasswordUpdate) check() error {
	if v, ok := upu.mutation.UserID(); ok {
		if err := userpassword.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserPassword.user_id": %w`, err)}
		}
	}
	return nil
}

func (upu *UserPasswordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := upu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(userpassword.Table, userpassword.Columns, sqlgraph.NewFieldSpec(userpassword.FieldID, field.TypeInt))
	if ps := upu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := upu.mutation.UserID(); ok {
		_spec.SetField(userpassword.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := upu.mutation.AddedUserID(); ok {
		_spec.AddField(userpassword.FieldUserID, field.TypeInt64, value)
	}
	if upu.mutation.UserIDCleared() {
		_spec.ClearField(userpassword.FieldUserID, field.TypeInt64)
	}
	if value, ok := upu.mutation.Salt(); ok {
		_spec.SetField(userpassword.FieldSalt, field.TypeString, value)
	}
	if value, ok := upu.mutation.Pwd(); ok {
		_spec.SetField(userpassword.FieldPwd, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, upu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpassword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	upu.mutation.done = true
	return n, nil
}

// UserPasswordUpdateOne is the builder for updating a single UserPassword entity.
type UserPasswordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserPasswordMutation
}

// SetUserID sets the "user_id" field.
func (upuo *UserPasswordUpdateOne) SetUserID(i int64) *UserPasswordUpdateOne {
	upuo.mutation.ResetUserID()
	upuo.mutation.SetUserID(i)
	return upuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (upuo *UserPasswordUpdateOne) SetNillableUserID(i *int64) *UserPasswordUpdateOne {
	if i != nil {
		upuo.SetUserID(*i)
	}
	return upuo
}

// AddUserID adds i to the "user_id" field.
func (upuo *UserPasswordUpdateOne) AddUserID(i int64) *UserPasswordUpdateOne {
	upuo.mutation.AddUserID(i)
	return upuo
}

// ClearUserID clears the value of the "user_id" field.
func (upuo *UserPasswordUpdateOne) ClearUserID() *UserPasswordUpdateOne {
	upuo.mutation.ClearUserID()
	return upuo
}

// SetSalt sets the "salt" field.
func (upuo *UserPasswordUpdateOne) SetSalt(s string) *UserPasswordUpdateOne {
	upuo.mutation.SetSalt(s)
	return upuo
}

// SetPwd sets the "pwd" field.
func (upuo *UserPasswordUpdateOne) SetPwd(s string) *UserPasswordUpdateOne {
	upuo.mutation.SetPwd(s)
	return upuo
}

// Mutation returns the UserPasswordMutation object of the builder.
func (upuo *UserPasswordUpdateOne) Mutation() *UserPasswordMutation {
	return upuo.mutation
}

// Where appends a list predicates to the UserPasswordUpdate builder.
func (upuo *UserPasswordUpdateOne) Where(ps ...predicate.UserPassword) *UserPasswordUpdateOne {
	upuo.mutation.Where(ps...)
	return upuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (upuo *UserPasswordUpdateOne) Select(field string, fields ...string) *UserPasswordUpdateOne {
	upuo.fields = append([]string{field}, fields...)
	return upuo
}

// Save executes the query and returns the updated UserPassword entity.
func (upuo *UserPasswordUpdateOne) Save(ctx context.Context) (*UserPassword, error) {
	return withHooks(ctx, upuo.sqlSave, upuo.mutation, upuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (upuo *UserPasswordUpdateOne) SaveX(ctx context.Context) *UserPassword {
	node, err := upuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (upuo *UserPasswordUpdateOne) Exec(ctx context.Context) error {
	_, err := upuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upuo *UserPasswordUpdateOne) ExecX(ctx context.Context) {
	if err := upuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upuo *UserPasswordUpdateOne) check() error {
	if v, ok := upuo.mutation.UserID(); ok {
		if err := userpassword.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserPassword.user_id": %w`, err)}
		}
	}
	return nil
}

func (upuo *UserPasswordUpdateOne) sqlSave(ctx context.Context) (_node *UserPassword, err error) {
	if err := upuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userpassword.Table, userpassword.Columns, sqlgraph.NewFieldSpec(userpassword.FieldID, field.TypeInt))
	id, ok := upuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserPassword.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := upuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpassword.FieldID)
		for _, f := range fields {
			if !userpassword.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userpassword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := upuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := upuo.mutation.UserID(); ok {
		_spec.SetField(userpassword.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := upuo.mutation.AddedUserID(); ok {
		_spec.AddField(userpassword.FieldUserID, field.TypeInt64, value)
	}
	if upuo.mutation.UserIDCleared() {
		_spec.ClearField(userpassword.FieldUserID, field.TypeInt64)
	}
	if value, ok := upuo.mutation.Salt(); ok {
		_spec.SetField(userpassword.FieldSalt, field.TypeString, value)
	}
	if value, ok := upuo.mutation.Pwd(); ok {
		_spec.SetField(userpassword.FieldPwd, field.TypeString, value)
	}
	_node = &UserPassword{config: upuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, upuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpassword.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	upuo.mutation.done = true
	return _node, nil
}
