// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"juice/internal/data/ent/predicate"
	"juice/internal/data/ent/userfollowinfo"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserFollowInfoQuery is the builder for querying UserFollowInfo entities.
type UserFollowInfoQuery struct {
	config
	ctx        *QueryContext
	order      []userfollowinfo.OrderOption
	inters     []Interceptor
	predicates []predicate.UserFollowInfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserFollowInfoQuery builder.
func (ufiq *UserFollowInfoQuery) Where(ps ...predicate.UserFollowInfo) *UserFollowInfoQuery {
	ufiq.predicates = append(ufiq.predicates, ps...)
	return ufiq
}

// Limit the number of records to be returned by this query.
func (ufiq *UserFollowInfoQuery) Limit(limit int) *UserFollowInfoQuery {
	ufiq.ctx.Limit = &limit
	return ufiq
}

// Offset to start from.
func (ufiq *UserFollowInfoQuery) Offset(offset int) *UserFollowInfoQuery {
	ufiq.ctx.Offset = &offset
	return ufiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ufiq *UserFollowInfoQuery) Unique(unique bool) *UserFollowInfoQuery {
	ufiq.ctx.Unique = &unique
	return ufiq
}

// Order specifies how the records should be ordered.
func (ufiq *UserFollowInfoQuery) Order(o ...userfollowinfo.OrderOption) *UserFollowInfoQuery {
	ufiq.order = append(ufiq.order, o...)
	return ufiq
}

// First returns the first UserFollowInfo entity from the query.
// Returns a *NotFoundError when no UserFollowInfo was found.
func (ufiq *UserFollowInfoQuery) First(ctx context.Context) (*UserFollowInfo, error) {
	nodes, err := ufiq.Limit(1).All(setContextOp(ctx, ufiq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userfollowinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ufiq *UserFollowInfoQuery) FirstX(ctx context.Context) *UserFollowInfo {
	node, err := ufiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserFollowInfo ID from the query.
// Returns a *NotFoundError when no UserFollowInfo ID was found.
func (ufiq *UserFollowInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ufiq.Limit(1).IDs(setContextOp(ctx, ufiq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userfollowinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ufiq *UserFollowInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := ufiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserFollowInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserFollowInfo entity is found.
// Returns a *NotFoundError when no UserFollowInfo entities are found.
func (ufiq *UserFollowInfoQuery) Only(ctx context.Context) (*UserFollowInfo, error) {
	nodes, err := ufiq.Limit(2).All(setContextOp(ctx, ufiq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userfollowinfo.Label}
	default:
		return nil, &NotSingularError{userfollowinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ufiq *UserFollowInfoQuery) OnlyX(ctx context.Context) *UserFollowInfo {
	node, err := ufiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserFollowInfo ID in the query.
// Returns a *NotSingularError when more than one UserFollowInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (ufiq *UserFollowInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ufiq.Limit(2).IDs(setContextOp(ctx, ufiq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userfollowinfo.Label}
	default:
		err = &NotSingularError{userfollowinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ufiq *UserFollowInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := ufiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserFollowInfos.
func (ufiq *UserFollowInfoQuery) All(ctx context.Context) ([]*UserFollowInfo, error) {
	ctx = setContextOp(ctx, ufiq.ctx, "All")
	if err := ufiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserFollowInfo, *UserFollowInfoQuery]()
	return withInterceptors[[]*UserFollowInfo](ctx, ufiq, qr, ufiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ufiq *UserFollowInfoQuery) AllX(ctx context.Context) []*UserFollowInfo {
	nodes, err := ufiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserFollowInfo IDs.
func (ufiq *UserFollowInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ufiq.ctx.Unique == nil && ufiq.path != nil {
		ufiq.Unique(true)
	}
	ctx = setContextOp(ctx, ufiq.ctx, "IDs")
	if err = ufiq.Select(userfollowinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ufiq *UserFollowInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := ufiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ufiq *UserFollowInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ufiq.ctx, "Count")
	if err := ufiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ufiq, querierCount[*UserFollowInfoQuery](), ufiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ufiq *UserFollowInfoQuery) CountX(ctx context.Context) int {
	count, err := ufiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ufiq *UserFollowInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ufiq.ctx, "Exist")
	switch _, err := ufiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ufiq *UserFollowInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := ufiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserFollowInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ufiq *UserFollowInfoQuery) Clone() *UserFollowInfoQuery {
	if ufiq == nil {
		return nil
	}
	return &UserFollowInfoQuery{
		config:     ufiq.config,
		ctx:        ufiq.ctx.Clone(),
		order:      append([]userfollowinfo.OrderOption{}, ufiq.order...),
		inters:     append([]Interceptor{}, ufiq.inters...),
		predicates: append([]predicate.UserFollowInfo{}, ufiq.predicates...),
		// clone intermediate query.
		sql:  ufiq.sql.Clone(),
		path: ufiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uint64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserFollowInfo.Query().
//		GroupBy(userfollowinfo.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ufiq *UserFollowInfoQuery) GroupBy(field string, fields ...string) *UserFollowInfoGroupBy {
	ufiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserFollowInfoGroupBy{build: ufiq}
	grbuild.flds = &ufiq.ctx.Fields
	grbuild.label = userfollowinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uint64 `json:"user_id,omitempty"`
//	}
//
//	client.UserFollowInfo.Query().
//		Select(userfollowinfo.FieldUserID).
//		Scan(ctx, &v)
func (ufiq *UserFollowInfoQuery) Select(fields ...string) *UserFollowInfoSelect {
	ufiq.ctx.Fields = append(ufiq.ctx.Fields, fields...)
	sbuild := &UserFollowInfoSelect{UserFollowInfoQuery: ufiq}
	sbuild.label = userfollowinfo.Label
	sbuild.flds, sbuild.scan = &ufiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserFollowInfoSelect configured with the given aggregations.
func (ufiq *UserFollowInfoQuery) Aggregate(fns ...AggregateFunc) *UserFollowInfoSelect {
	return ufiq.Select().Aggregate(fns...)
}

func (ufiq *UserFollowInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ufiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ufiq); err != nil {
				return err
			}
		}
	}
	for _, f := range ufiq.ctx.Fields {
		if !userfollowinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ufiq.path != nil {
		prev, err := ufiq.path(ctx)
		if err != nil {
			return err
		}
		ufiq.sql = prev
	}
	return nil
}

func (ufiq *UserFollowInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserFollowInfo, error) {
	var (
		nodes = []*UserFollowInfo{}
		_spec = ufiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserFollowInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserFollowInfo{config: ufiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ufiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ufiq *UserFollowInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ufiq.querySpec()
	_spec.Node.Columns = ufiq.ctx.Fields
	if len(ufiq.ctx.Fields) > 0 {
		_spec.Unique = ufiq.ctx.Unique != nil && *ufiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ufiq.driver, _spec)
}

func (ufiq *UserFollowInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userfollowinfo.Table, userfollowinfo.Columns, sqlgraph.NewFieldSpec(userfollowinfo.FieldID, field.TypeInt))
	_spec.From = ufiq.sql
	if unique := ufiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ufiq.path != nil {
		_spec.Unique = true
	}
	if fields := ufiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userfollowinfo.FieldID)
		for i := range fields {
			if fields[i] != userfollowinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ufiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ufiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ufiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ufiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ufiq *UserFollowInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ufiq.driver.Dialect())
	t1 := builder.Table(userfollowinfo.Table)
	columns := ufiq.ctx.Fields
	if len(columns) == 0 {
		columns = userfollowinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ufiq.sql != nil {
		selector = ufiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ufiq.ctx.Unique != nil && *ufiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ufiq.predicates {
		p(selector)
	}
	for _, p := range ufiq.order {
		p(selector)
	}
	if offset := ufiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ufiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserFollowInfoGroupBy is the group-by builder for UserFollowInfo entities.
type UserFollowInfoGroupBy struct {
	selector
	build *UserFollowInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ufigb *UserFollowInfoGroupBy) Aggregate(fns ...AggregateFunc) *UserFollowInfoGroupBy {
	ufigb.fns = append(ufigb.fns, fns...)
	return ufigb
}

// Scan applies the selector query and scans the result into the given value.
func (ufigb *UserFollowInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ufigb.build.ctx, "GroupBy")
	if err := ufigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserFollowInfoQuery, *UserFollowInfoGroupBy](ctx, ufigb.build, ufigb, ufigb.build.inters, v)
}

func (ufigb *UserFollowInfoGroupBy) sqlScan(ctx context.Context, root *UserFollowInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ufigb.fns))
	for _, fn := range ufigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ufigb.flds)+len(ufigb.fns))
		for _, f := range *ufigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ufigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ufigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserFollowInfoSelect is the builder for selecting fields of UserFollowInfo entities.
type UserFollowInfoSelect struct {
	*UserFollowInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ufis *UserFollowInfoSelect) Aggregate(fns ...AggregateFunc) *UserFollowInfoSelect {
	ufis.fns = append(ufis.fns, fns...)
	return ufis
}

// Scan applies the selector query and scans the result into the given value.
func (ufis *UserFollowInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ufis.ctx, "Select")
	if err := ufis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserFollowInfoQuery, *UserFollowInfoSelect](ctx, ufis.UserFollowInfoQuery, ufis, ufis.inters, v)
}

func (ufis *UserFollowInfoSelect) sqlScan(ctx context.Context, root *UserFollowInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ufis.fns))
	for _, fn := range ufis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ufis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ufis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
