// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"juice/internal/data/ent/predicate"
	"juice/internal/data/ent/videometadata"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VideoMetadataQuery is the builder for querying VideoMetadata entities.
type VideoMetadataQuery struct {
	config
	ctx        *QueryContext
	order      []videometadata.OrderOption
	inters     []Interceptor
	predicates []predicate.VideoMetadata
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VideoMetadataQuery builder.
func (vmq *VideoMetadataQuery) Where(ps ...predicate.VideoMetadata) *VideoMetadataQuery {
	vmq.predicates = append(vmq.predicates, ps...)
	return vmq
}

// Limit the number of records to be returned by this query.
func (vmq *VideoMetadataQuery) Limit(limit int) *VideoMetadataQuery {
	vmq.ctx.Limit = &limit
	return vmq
}

// Offset to start from.
func (vmq *VideoMetadataQuery) Offset(offset int) *VideoMetadataQuery {
	vmq.ctx.Offset = &offset
	return vmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vmq *VideoMetadataQuery) Unique(unique bool) *VideoMetadataQuery {
	vmq.ctx.Unique = &unique
	return vmq
}

// Order specifies how the records should be ordered.
func (vmq *VideoMetadataQuery) Order(o ...videometadata.OrderOption) *VideoMetadataQuery {
	vmq.order = append(vmq.order, o...)
	return vmq
}

// First returns the first VideoMetadata entity from the query.
// Returns a *NotFoundError when no VideoMetadata was found.
func (vmq *VideoMetadataQuery) First(ctx context.Context) (*VideoMetadata, error) {
	nodes, err := vmq.Limit(1).All(setContextOp(ctx, vmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{videometadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vmq *VideoMetadataQuery) FirstX(ctx context.Context) *VideoMetadata {
	node, err := vmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VideoMetadata ID from the query.
// Returns a *NotFoundError when no VideoMetadata ID was found.
func (vmq *VideoMetadataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vmq.Limit(1).IDs(setContextOp(ctx, vmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{videometadata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vmq *VideoMetadataQuery) FirstIDX(ctx context.Context) int {
	id, err := vmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VideoMetadata entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VideoMetadata entity is found.
// Returns a *NotFoundError when no VideoMetadata entities are found.
func (vmq *VideoMetadataQuery) Only(ctx context.Context) (*VideoMetadata, error) {
	nodes, err := vmq.Limit(2).All(setContextOp(ctx, vmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{videometadata.Label}
	default:
		return nil, &NotSingularError{videometadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vmq *VideoMetadataQuery) OnlyX(ctx context.Context) *VideoMetadata {
	node, err := vmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VideoMetadata ID in the query.
// Returns a *NotSingularError when more than one VideoMetadata ID is found.
// Returns a *NotFoundError when no entities are found.
func (vmq *VideoMetadataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vmq.Limit(2).IDs(setContextOp(ctx, vmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{videometadata.Label}
	default:
		err = &NotSingularError{videometadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vmq *VideoMetadataQuery) OnlyIDX(ctx context.Context) int {
	id, err := vmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VideoMetadataSlice.
func (vmq *VideoMetadataQuery) All(ctx context.Context) ([]*VideoMetadata, error) {
	ctx = setContextOp(ctx, vmq.ctx, "All")
	if err := vmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VideoMetadata, *VideoMetadataQuery]()
	return withInterceptors[[]*VideoMetadata](ctx, vmq, qr, vmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vmq *VideoMetadataQuery) AllX(ctx context.Context) []*VideoMetadata {
	nodes, err := vmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VideoMetadata IDs.
func (vmq *VideoMetadataQuery) IDs(ctx context.Context) (ids []int, err error) {
	if vmq.ctx.Unique == nil && vmq.path != nil {
		vmq.Unique(true)
	}
	ctx = setContextOp(ctx, vmq.ctx, "IDs")
	if err = vmq.Select(videometadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vmq *VideoMetadataQuery) IDsX(ctx context.Context) []int {
	ids, err := vmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vmq *VideoMetadataQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vmq.ctx, "Count")
	if err := vmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vmq, querierCount[*VideoMetadataQuery](), vmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vmq *VideoMetadataQuery) CountX(ctx context.Context) int {
	count, err := vmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vmq *VideoMetadataQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vmq.ctx, "Exist")
	switch _, err := vmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vmq *VideoMetadataQuery) ExistX(ctx context.Context) bool {
	exist, err := vmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VideoMetadataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vmq *VideoMetadataQuery) Clone() *VideoMetadataQuery {
	if vmq == nil {
		return nil
	}
	return &VideoMetadataQuery{
		config:     vmq.config,
		ctx:        vmq.ctx.Clone(),
		order:      append([]videometadata.OrderOption{}, vmq.order...),
		inters:     append([]Interceptor{}, vmq.inters...),
		predicates: append([]predicate.VideoMetadata{}, vmq.predicates...),
		// clone intermediate query.
		sql:  vmq.sql.Clone(),
		path: vmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VideoID int64 `json:"video_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VideoMetadata.Query().
//		GroupBy(videometadata.FieldVideoID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vmq *VideoMetadataQuery) GroupBy(field string, fields ...string) *VideoMetadataGroupBy {
	vmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VideoMetadataGroupBy{build: vmq}
	grbuild.flds = &vmq.ctx.Fields
	grbuild.label = videometadata.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VideoID int64 `json:"video_id,omitempty"`
//	}
//
//	client.VideoMetadata.Query().
//		Select(videometadata.FieldVideoID).
//		Scan(ctx, &v)
func (vmq *VideoMetadataQuery) Select(fields ...string) *VideoMetadataSelect {
	vmq.ctx.Fields = append(vmq.ctx.Fields, fields...)
	sbuild := &VideoMetadataSelect{VideoMetadataQuery: vmq}
	sbuild.label = videometadata.Label
	sbuild.flds, sbuild.scan = &vmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VideoMetadataSelect configured with the given aggregations.
func (vmq *VideoMetadataQuery) Aggregate(fns ...AggregateFunc) *VideoMetadataSelect {
	return vmq.Select().Aggregate(fns...)
}

func (vmq *VideoMetadataQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vmq); err != nil {
				return err
			}
		}
	}
	for _, f := range vmq.ctx.Fields {
		if !videometadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vmq.path != nil {
		prev, err := vmq.path(ctx)
		if err != nil {
			return err
		}
		vmq.sql = prev
	}
	return nil
}

func (vmq *VideoMetadataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VideoMetadata, error) {
	var (
		nodes = []*VideoMetadata{}
		_spec = vmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VideoMetadata).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VideoMetadata{config: vmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (vmq *VideoMetadataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vmq.querySpec()
	_spec.Node.Columns = vmq.ctx.Fields
	if len(vmq.ctx.Fields) > 0 {
		_spec.Unique = vmq.ctx.Unique != nil && *vmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vmq.driver, _spec)
}

func (vmq *VideoMetadataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(videometadata.Table, videometadata.Columns, sqlgraph.NewFieldSpec(videometadata.FieldID, field.TypeInt))
	_spec.From = vmq.sql
	if unique := vmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vmq.path != nil {
		_spec.Unique = true
	}
	if fields := vmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videometadata.FieldID)
		for i := range fields {
			if fields[i] != videometadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vmq *VideoMetadataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vmq.driver.Dialect())
	t1 := builder.Table(videometadata.Table)
	columns := vmq.ctx.Fields
	if len(columns) == 0 {
		columns = videometadata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vmq.sql != nil {
		selector = vmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vmq.ctx.Unique != nil && *vmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vmq.predicates {
		p(selector)
	}
	for _, p := range vmq.order {
		p(selector)
	}
	if offset := vmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VideoMetadataGroupBy is the group-by builder for VideoMetadata entities.
type VideoMetadataGroupBy struct {
	selector
	build *VideoMetadataQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vmgb *VideoMetadataGroupBy) Aggregate(fns ...AggregateFunc) *VideoMetadataGroupBy {
	vmgb.fns = append(vmgb.fns, fns...)
	return vmgb
}

// Scan applies the selector query and scans the result into the given value.
func (vmgb *VideoMetadataGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vmgb.build.ctx, "GroupBy")
	if err := vmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VideoMetadataQuery, *VideoMetadataGroupBy](ctx, vmgb.build, vmgb, vmgb.build.inters, v)
}

func (vmgb *VideoMetadataGroupBy) sqlScan(ctx context.Context, root *VideoMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vmgb.fns))
	for _, fn := range vmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vmgb.flds)+len(vmgb.fns))
		for _, f := range *vmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VideoMetadataSelect is the builder for selecting fields of VideoMetadata entities.
type VideoMetadataSelect struct {
	*VideoMetadataQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vms *VideoMetadataSelect) Aggregate(fns ...AggregateFunc) *VideoMetadataSelect {
	vms.fns = append(vms.fns, fns...)
	return vms
}

// Scan applies the selector query and scans the result into the given value.
func (vms *VideoMetadataSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vms.ctx, "Select")
	if err := vms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VideoMetadataQuery, *VideoMetadataSelect](ctx, vms.VideoMetadataQuery, vms, vms.inters, v)
}

func (vms *VideoMetadataSelect) sqlScan(ctx context.Context, root *VideoMetadataQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vms.fns))
	for _, fn := range vms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
