// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"juice/internal/data/ent/videometadata"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// VideoMetadata is the model entity for the VideoMetadata schema.
type VideoMetadata struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// VideoID holds the value of the "video_id" field.
	VideoID int64 `json:"video_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CoverURL holds the value of the "cover_url" field.
	CoverURL string `json:"cover_url,omitempty"`
	// VideoURL holds the value of the "video_url" field.
	VideoURL string `json:"video_url,omitempty"`
	// VideoIntro holds the value of the "video_intro" field.
	VideoIntro string `json:"video_intro,omitempty"`
	// VideoType holds the value of the "video_type" field.
	VideoType int64 `json:"video_type,omitempty"`
	// PublishAddress holds the value of the "publish_address" field.
	PublishAddress int32 `json:"publish_address,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime   time.Time `json:"update_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoMetadata) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videometadata.FieldID, videometadata.FieldVideoID, videometadata.FieldUserID, videometadata.FieldVideoType, videometadata.FieldPublishAddress:
			values[i] = new(sql.NullInt64)
		case videometadata.FieldCoverURL, videometadata.FieldVideoURL, videometadata.FieldVideoIntro:
			values[i] = new(sql.NullString)
		case videometadata.FieldCreateTime, videometadata.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoMetadata fields.
func (vm *VideoMetadata) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videometadata.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			vm.ID = int(value.Int64)
		case videometadata.FieldVideoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_id", values[i])
			} else if value.Valid {
				vm.VideoID = value.Int64
			}
		case videometadata.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				vm.UserID = value.Int64
			}
		case videometadata.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				vm.CoverURL = value.String
			}
		case videometadata.FieldVideoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_url", values[i])
			} else if value.Valid {
				vm.VideoURL = value.String
			}
		case videometadata.FieldVideoIntro:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_intro", values[i])
			} else if value.Valid {
				vm.VideoIntro = value.String
			}
		case videometadata.FieldVideoType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_type", values[i])
			} else if value.Valid {
				vm.VideoType = value.Int64
			}
		case videometadata.FieldPublishAddress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field publish_address", values[i])
			} else if value.Valid {
				vm.PublishAddress = int32(value.Int64)
			}
		case videometadata.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				vm.CreateTime = value.Time
			}
		case videometadata.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				vm.UpdateTime = value.Time
			}
		default:
			vm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoMetadata.
// This includes values selected through modifiers, order, etc.
func (vm *VideoMetadata) Value(name string) (ent.Value, error) {
	return vm.selectValues.Get(name)
}

// Update returns a builder for updating this VideoMetadata.
// Note that you need to call VideoMetadata.Unwrap() before calling this method if this VideoMetadata
// was returned from a transaction, and the transaction was committed or rolled back.
func (vm *VideoMetadata) Update() *VideoMetadataUpdateOne {
	return NewVideoMetadataClient(vm.config).UpdateOne(vm)
}

// Unwrap unwraps the VideoMetadata entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (vm *VideoMetadata) Unwrap() *VideoMetadata {
	_tx, ok := vm.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoMetadata is not a transactional entity")
	}
	vm.config.driver = _tx.drv
	return vm
}

// String implements the fmt.Stringer.
func (vm *VideoMetadata) String() string {
	var builder strings.Builder
	builder.WriteString("VideoMetadata(")
	builder.WriteString(fmt.Sprintf("id=%v, ", vm.ID))
	builder.WriteString("video_id=")
	builder.WriteString(fmt.Sprintf("%v", vm.VideoID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", vm.UserID))
	builder.WriteString(", ")
	builder.WriteString("cover_url=")
	builder.WriteString(vm.CoverURL)
	builder.WriteString(", ")
	builder.WriteString("video_url=")
	builder.WriteString(vm.VideoURL)
	builder.WriteString(", ")
	builder.WriteString("video_intro=")
	builder.WriteString(vm.VideoIntro)
	builder.WriteString(", ")
	builder.WriteString("video_type=")
	builder.WriteString(fmt.Sprintf("%v", vm.VideoType))
	builder.WriteString(", ")
	builder.WriteString("publish_address=")
	builder.WriteString(fmt.Sprintf("%v", vm.PublishAddress))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(vm.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(vm.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VideoMetadataSlice is a parsable slice of VideoMetadata.
type VideoMetadataSlice []*VideoMetadata
