// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"juice/internal/data/ent/predicate"
	"juice/internal/data/ent/videocollection"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VideoCollectionUpdate is the builder for updating VideoCollection entities.
type VideoCollectionUpdate struct {
	config
	hooks    []Hook
	mutation *VideoCollectionMutation
}

// Where appends a list predicates to the VideoCollectionUpdate builder.
func (vcu *VideoCollectionUpdate) Where(ps ...predicate.VideoCollection) *VideoCollectionUpdate {
	vcu.mutation.Where(ps...)
	return vcu
}

// SetUserID sets the "user_id" field.
func (vcu *VideoCollectionUpdate) SetUserID(i int) *VideoCollectionUpdate {
	vcu.mutation.ResetUserID()
	vcu.mutation.SetUserID(i)
	return vcu
}

// AddUserID adds i to the "user_id" field.
func (vcu *VideoCollectionUpdate) AddUserID(i int) *VideoCollectionUpdate {
	vcu.mutation.AddUserID(i)
	return vcu
}

// SetVideoID sets the "video_id" field.
func (vcu *VideoCollectionUpdate) SetVideoID(i int) *VideoCollectionUpdate {
	vcu.mutation.ResetVideoID()
	vcu.mutation.SetVideoID(i)
	return vcu
}

// AddVideoID adds i to the "video_id" field.
func (vcu *VideoCollectionUpdate) AddVideoID(i int) *VideoCollectionUpdate {
	vcu.mutation.AddVideoID(i)
	return vcu
}

// SetStatus sets the "status" field.
func (vcu *VideoCollectionUpdate) SetStatus(i int8) *VideoCollectionUpdate {
	vcu.mutation.ResetStatus()
	vcu.mutation.SetStatus(i)
	return vcu
}

// AddStatus adds i to the "status" field.
func (vcu *VideoCollectionUpdate) AddStatus(i int8) *VideoCollectionUpdate {
	vcu.mutation.AddStatus(i)
	return vcu
}

// SetCreateTime sets the "create_time" field.
func (vcu *VideoCollectionUpdate) SetCreateTime(t time.Time) *VideoCollectionUpdate {
	vcu.mutation.SetCreateTime(t)
	return vcu
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (vcu *VideoCollectionUpdate) SetNillableCreateTime(t *time.Time) *VideoCollectionUpdate {
	if t != nil {
		vcu.SetCreateTime(*t)
	}
	return vcu
}

// ClearCreateTime clears the value of the "create_time" field.
func (vcu *VideoCollectionUpdate) ClearCreateTime() *VideoCollectionUpdate {
	vcu.mutation.ClearCreateTime()
	return vcu
}

// SetUpdateTime sets the "update_time" field.
func (vcu *VideoCollectionUpdate) SetUpdateTime(t time.Time) *VideoCollectionUpdate {
	vcu.mutation.SetUpdateTime(t)
	return vcu
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (vcu *VideoCollectionUpdate) SetNillableUpdateTime(t *time.Time) *VideoCollectionUpdate {
	if t != nil {
		vcu.SetUpdateTime(*t)
	}
	return vcu
}

// ClearUpdateTime clears the value of the "update_time" field.
func (vcu *VideoCollectionUpdate) ClearUpdateTime() *VideoCollectionUpdate {
	vcu.mutation.ClearUpdateTime()
	return vcu
}

// Mutation returns the VideoCollectionMutation object of the builder.
func (vcu *VideoCollectionUpdate) Mutation() *VideoCollectionMutation {
	return vcu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vcu *VideoCollectionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, vcu.sqlSave, vcu.mutation, vcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vcu *VideoCollectionUpdate) SaveX(ctx context.Context) int {
	affected, err := vcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vcu *VideoCollectionUpdate) Exec(ctx context.Context) error {
	_, err := vcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vcu *VideoCollectionUpdate) ExecX(ctx context.Context) {
	if err := vcu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vcu *VideoCollectionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(videocollection.Table, videocollection.Columns, sqlgraph.NewFieldSpec(videocollection.FieldID, field.TypeInt))
	if ps := vcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vcu.mutation.UserID(); ok {
		_spec.SetField(videocollection.FieldUserID, field.TypeInt, value)
	}
	if value, ok := vcu.mutation.AddedUserID(); ok {
		_spec.AddField(videocollection.FieldUserID, field.TypeInt, value)
	}
	if value, ok := vcu.mutation.VideoID(); ok {
		_spec.SetField(videocollection.FieldVideoID, field.TypeInt, value)
	}
	if value, ok := vcu.mutation.AddedVideoID(); ok {
		_spec.AddField(videocollection.FieldVideoID, field.TypeInt, value)
	}
	if value, ok := vcu.mutation.Status(); ok {
		_spec.SetField(videocollection.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := vcu.mutation.AddedStatus(); ok {
		_spec.AddField(videocollection.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := vcu.mutation.CreateTime(); ok {
		_spec.SetField(videocollection.FieldCreateTime, field.TypeTime, value)
	}
	if vcu.mutation.CreateTimeCleared() {
		_spec.ClearField(videocollection.FieldCreateTime, field.TypeTime)
	}
	if value, ok := vcu.mutation.UpdateTime(); ok {
		_spec.SetField(videocollection.FieldUpdateTime, field.TypeTime, value)
	}
	if vcu.mutation.UpdateTimeCleared() {
		_spec.ClearField(videocollection.FieldUpdateTime, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videocollection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vcu.mutation.done = true
	return n, nil
}

// VideoCollectionUpdateOne is the builder for updating a single VideoCollection entity.
type VideoCollectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoCollectionMutation
}

// SetUserID sets the "user_id" field.
func (vcuo *VideoCollectionUpdateOne) SetUserID(i int) *VideoCollectionUpdateOne {
	vcuo.mutation.ResetUserID()
	vcuo.mutation.SetUserID(i)
	return vcuo
}

// AddUserID adds i to the "user_id" field.
func (vcuo *VideoCollectionUpdateOne) AddUserID(i int) *VideoCollectionUpdateOne {
	vcuo.mutation.AddUserID(i)
	return vcuo
}

// SetVideoID sets the "video_id" field.
func (vcuo *VideoCollectionUpdateOne) SetVideoID(i int) *VideoCollectionUpdateOne {
	vcuo.mutation.ResetVideoID()
	vcuo.mutation.SetVideoID(i)
	return vcuo
}

// AddVideoID adds i to the "video_id" field.
func (vcuo *VideoCollectionUpdateOne) AddVideoID(i int) *VideoCollectionUpdateOne {
	vcuo.mutation.AddVideoID(i)
	return vcuo
}

// SetStatus sets the "status" field.
func (vcuo *VideoCollectionUpdateOne) SetStatus(i int8) *VideoCollectionUpdateOne {
	vcuo.mutation.ResetStatus()
	vcuo.mutation.SetStatus(i)
	return vcuo
}

// AddStatus adds i to the "status" field.
func (vcuo *VideoCollectionUpdateOne) AddStatus(i int8) *VideoCollectionUpdateOne {
	vcuo.mutation.AddStatus(i)
	return vcuo
}

// SetCreateTime sets the "create_time" field.
func (vcuo *VideoCollectionUpdateOne) SetCreateTime(t time.Time) *VideoCollectionUpdateOne {
	vcuo.mutation.SetCreateTime(t)
	return vcuo
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (vcuo *VideoCollectionUpdateOne) SetNillableCreateTime(t *time.Time) *VideoCollectionUpdateOne {
	if t != nil {
		vcuo.SetCreateTime(*t)
	}
	return vcuo
}

// ClearCreateTime clears the value of the "create_time" field.
func (vcuo *VideoCollectionUpdateOne) ClearCreateTime() *VideoCollectionUpdateOne {
	vcuo.mutation.ClearCreateTime()
	return vcuo
}

// SetUpdateTime sets the "update_time" field.
func (vcuo *VideoCollectionUpdateOne) SetUpdateTime(t time.Time) *VideoCollectionUpdateOne {
	vcuo.mutation.SetUpdateTime(t)
	return vcuo
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (vcuo *VideoCollectionUpdateOne) SetNillableUpdateTime(t *time.Time) *VideoCollectionUpdateOne {
	if t != nil {
		vcuo.SetUpdateTime(*t)
	}
	return vcuo
}

// ClearUpdateTime clears the value of the "update_time" field.
func (vcuo *VideoCollectionUpdateOne) ClearUpdateTime() *VideoCollectionUpdateOne {
	vcuo.mutation.ClearUpdateTime()
	return vcuo
}

// Mutation returns the VideoCollectionMutation object of the builder.
func (vcuo *VideoCollectionUpdateOne) Mutation() *VideoCollectionMutation {
	return vcuo.mutation
}

// Where appends a list predicates to the VideoCollectionUpdate builder.
func (vcuo *VideoCollectionUpdateOne) Where(ps ...predicate.VideoCollection) *VideoCollectionUpdateOne {
	vcuo.mutation.Where(ps...)
	return vcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vcuo *VideoCollectionUpdateOne) Select(field string, fields ...string) *VideoCollectionUpdateOne {
	vcuo.fields = append([]string{field}, fields...)
	return vcuo
}

// Save executes the query and returns the updated VideoCollection entity.
func (vcuo *VideoCollectionUpdateOne) Save(ctx context.Context) (*VideoCollection, error) {
	return withHooks(ctx, vcuo.sqlSave, vcuo.mutation, vcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vcuo *VideoCollectionUpdateOne) SaveX(ctx context.Context) *VideoCollection {
	node, err := vcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vcuo *VideoCollectionUpdateOne) Exec(ctx context.Context) error {
	_, err := vcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vcuo *VideoCollectionUpdateOne) ExecX(ctx context.Context) {
	if err := vcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vcuo *VideoCollectionUpdateOne) sqlSave(ctx context.Context) (_node *VideoCollection, err error) {
	_spec := sqlgraph.NewUpdateSpec(videocollection.Table, videocollection.Columns, sqlgraph.NewFieldSpec(videocollection.FieldID, field.TypeInt))
	id, ok := vcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoCollection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videocollection.FieldID)
		for _, f := range fields {
			if !videocollection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videocollection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vcuo.mutation.UserID(); ok {
		_spec.SetField(videocollection.FieldUserID, field.TypeInt, value)
	}
	if value, ok := vcuo.mutation.AddedUserID(); ok {
		_spec.AddField(videocollection.FieldUserID, field.TypeInt, value)
	}
	if value, ok := vcuo.mutation.VideoID(); ok {
		_spec.SetField(videocollection.FieldVideoID, field.TypeInt, value)
	}
	if value, ok := vcuo.mutation.AddedVideoID(); ok {
		_spec.AddField(videocollection.FieldVideoID, field.TypeInt, value)
	}
	if value, ok := vcuo.mutation.Status(); ok {
		_spec.SetField(videocollection.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := vcuo.mutation.AddedStatus(); ok {
		_spec.AddField(videocollection.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := vcuo.mutation.CreateTime(); ok {
		_spec.SetField(videocollection.FieldCreateTime, field.TypeTime, value)
	}
	if vcuo.mutation.CreateTimeCleared() {
		_spec.ClearField(videocollection.FieldCreateTime, field.TypeTime)
	}
	if value, ok := vcuo.mutation.UpdateTime(); ok {
		_spec.SetField(videocollection.FieldUpdateTime, field.TypeTime, value)
	}
	if vcuo.mutation.UpdateTimeCleared() {
		_spec.ClearField(videocollection.FieldUpdateTime, field.TypeTime)
	}
	_node = &VideoCollection{config: vcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videocollection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vcuo.mutation.done = true
	return _node, nil
}
