// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"juice/internal/data/ent/predicate"
	"juice/internal/data/ent/videometadata"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VideoMetadataDelete is the builder for deleting a VideoMetadata entity.
type VideoMetadataDelete struct {
	config
	hooks    []Hook
	mutation *VideoMetadataMutation
}

// Where appends a list predicates to the VideoMetadataDelete builder.
func (vmd *VideoMetadataDelete) Where(ps ...predicate.VideoMetadata) *VideoMetadataDelete {
	vmd.mutation.Where(ps...)
	return vmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vmd *VideoMetadataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, vmd.sqlExec, vmd.mutation, vmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vmd *VideoMetadataDelete) ExecX(ctx context.Context) int {
	n, err := vmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vmd *VideoMetadataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(videometadata.Table, sqlgraph.NewFieldSpec(videometadata.FieldID, field.TypeInt))
	if ps := vmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vmd.mutation.done = true
	return affected, err
}

// VideoMetadataDeleteOne is the builder for deleting a single VideoMetadata entity.
type VideoMetadataDeleteOne struct {
	vmd *VideoMetadataDelete
}

// Where appends a list predicates to the VideoMetadataDelete builder.
func (vmdo *VideoMetadataDeleteOne) Where(ps ...predicate.VideoMetadata) *VideoMetadataDeleteOne {
	vmdo.vmd.mutation.Where(ps...)
	return vmdo
}

// Exec executes the deletion query.
func (vmdo *VideoMetadataDeleteOne) Exec(ctx context.Context) error {
	n, err := vmdo.vmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{videometadata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vmdo *VideoMetadataDeleteOne) ExecX(ctx context.Context) {
	if err := vmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
