// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type VideoCollection struct {
	ent.Schema
}

func (VideoCollection) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id"), field.Int("user_id"), field.Int("video_id"), field.Int8("status"), field.Time("create_time").Optional(), field.Time("update_time").Optional()}
}
func (VideoCollection) Edges() []ent.Edge {
	return nil
}
func (VideoCollection) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "video_collection"}}
}
