// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type VideoMetadatum struct {
	ent.Schema
}

func (VideoMetadatum) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int("video_id").Unique(), field.Int("user_id"), field.String("cover_url"), field.String("video_url"), field.String("video_intro").Optional(), field.Int("video_type"), field.Int32("publish_address"), field.Time("create_time").Optional(), field.Time("update_time").Optional()}
}
func (VideoMetadatum) Edges() []ent.Edge {
	return nil
}
func (VideoMetadatum) Annotations() []schema.Annotation {
	return nil
}
