// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UserBaseInfo is the predicate function for userbaseinfo builders.
type UserBaseInfo func(*sql.Selector)

// UserFollowInfo is the predicate function for userfollowinfo builders.
type UserFollowInfo func(*sql.Selector)

// UserPassword is the predicate function for userpassword builders.
type UserPassword func(*sql.Selector)

// VideoCollection is the predicate function for videocollection builders.
type VideoCollection func(*sql.Selector)

// VideoComment is the predicate function for videocomment builders.
type VideoComment func(*sql.Selector)

// VideoLike is the predicate function for videolike builders.
type VideoLike func(*sql.Selector)

// VideoMetadata is the predicate function for videometadata builders.
type VideoMetadata func(*sql.Selector)
