// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type UserBaseInfo struct {
	ent.Schema
}

func (UserBaseInfo) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id"), field.Uint64("user_id").Unique(), field.String("username").Unique(), field.Int8("sex"), field.Time("birth").Optional(), field.Int32("area"), field.String("user_profile").Optional(), field.String("user_profile_photo_url").Optional(), field.Int32("follow_count"), field.Int32("fan_count"), field.Time("create_time").Optional(), field.Time("update_time").Optional()}
}
func (UserBaseInfo) Edges() []ent.Edge {
	return nil
}
func (UserBaseInfo) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "user_base_info"}}
}
