// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type VideoComment struct {
	ent.Schema
}

func (VideoComment) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id"), field.Int("comment_id").Unique(), field.Int("pcomment_id"), field.Int("video_id"), field.Int("user_id"), field.String("comment_text").Optional(), field.Time("create_time").Optional(), field.Time("update_time").Optional()}
}
func (VideoComment) Edges() []ent.Edge {
	return nil
}
func (VideoComment) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "video_comment"}}
}
