// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"juice/public/data/ent/predicate"
	"juice/public/data/ent/videocomment"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VideoCommentDelete is the builder for deleting a VideoComment entity.
type VideoCommentDelete struct {
	config
	hooks    []Hook
	mutation *VideoCommentMutation
}

// Where appends a list predicates to the VideoCommentDelete builder.
func (vcd *VideoCommentDelete) Where(ps ...predicate.VideoComment) *VideoCommentDelete {
	vcd.mutation.Where(ps...)
	return vcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vcd *VideoCommentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, vcd.sqlExec, vcd.mutation, vcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vcd *VideoCommentDelete) ExecX(ctx context.Context) int {
	n, err := vcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vcd *VideoCommentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(videocomment.Table, sqlgraph.NewFieldSpec(videocomment.FieldID, field.TypeUint64))
	if ps := vcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vcd.mutation.done = true
	return affected, err
}

// VideoCommentDeleteOne is the builder for deleting a single VideoComment entity.
type VideoCommentDeleteOne struct {
	vcd *VideoCommentDelete
}

// Where appends a list predicates to the VideoCommentDelete builder.
func (vcdo *VideoCommentDeleteOne) Where(ps ...predicate.VideoComment) *VideoCommentDeleteOne {
	vcdo.vcd.mutation.Where(ps...)
	return vcdo
}

// Exec executes the deletion query.
func (vcdo *VideoCommentDeleteOne) Exec(ctx context.Context) error {
	n, err := vcdo.vcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{videocomment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vcdo *VideoCommentDeleteOne) ExecX(ctx context.Context) {
	if err := vcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
