// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type UserPassword struct {
	ent.Schema
}

func (UserPassword) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Uint64("user_id").Optional().Unique(), field.String("salt"), field.String("pwd"), field.Time("create_time").Optional(), field.Time("update_time").Optional()}
}
func (UserPassword) Edges() []ent.Edge {
	return nil
}
func (UserPassword) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "user_password"}}
}
