// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type UserFollowInfo struct {
	ent.Schema
}

func (UserFollowInfo) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id"), field.Uint64("user_id"), field.Uint64("follow_id"), field.Int8("status"), field.Time("create_time").Optional(), field.Time("update_time").Optional()}
}
func (UserFollowInfo) Edges() []ent.Edge {
	return nil
}
func (UserFollowInfo) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "user_follow_info"}}
}
